# Generated by Django 5.0.3 on 2024-03-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(),
        ),
    ]
