# Generated by Django 5.0.7 on 2024-07-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
