# Generated by Django 5.0.7 on 2024-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_reply_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_comment_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
